
unformatted = "/content/drive/MyDrive/tick"
unformatted_tick = "/content/drive/MyDrive/tick"
formatted = "/content/drive/MyDrive/tick/formatted"
intraday = "/content/drive/MyDrive/tick/formatted"

[yf_tickers]
GC_F = "GC=F"
ES_F = "ES=F"
NG_F = "NG=F"

[resampler]
file_name_format = "_"

[baskets]
Energy = [ "NG_F", "CL_F",]
Financials = [ "ES_F", "ZB_F",]
Agriculturals = [ "LE_F",]
PMs = [ "GC_F",]
Agris = [ "LE_F", "ZC_F",]

[aliases.unformatted]
GC_F = "GC_F.csv"
ES_F = "ES_F.csv"
NG_F = "NG_F.csv"
CL_F = "CL_F.csv"
ZB_F = "ZB_F.csv"
LE_F = "LE_F.csv"

[aliases.formatted]
ES_F = "ES_F.parquet"
CL_F = "CL_F.parquet"

[aliases.intraday]
GC_F = "GC_F.csv"
LE_F = "LE_F.csv"
ZC_F = "ZC_F.csv"
NG_F = "NG_F.csv"
ZB_F = "ZB_F.csv"
