[inititalization]
intraday_tfs = ['1h']
HAR = false
cluster = true


[cluster]
use_cluster = false
method = 'wkmeans'
k = 3
features_config = '.'
train_split = true
split_len = 0.8

[cluster.pca]
use_pca = true
pca_components = 3


[cluster.wkmeans]
k=3
max_iter = 20
tol = 1e-5
gamma = 5.0
mmd_pairs = 7
h1 = 300
h2 = 30


[types]
Volatility = true
Trend = true
Volume = true
Additional = true

[Volatility]
ATR = false
ATR_length = 42
hawkes = true
hawkes_mean = 168
kappa = 0.2
hawkes_signal_lb=72
normalize_range_len = 10
hawkes_binary_signal = true
hl_range = true
range_lengths = [20, 120, 240]
lagged_vol = false
vol_lags = [5]
lagged_semivariance=false
sv_lags = [1, 5]

[Volume]
relative_volume = true
rvol_days = 10
delta = true
delta_as_pct = true
VSA = true
vsa_cols = ['AskVolume']
vsa_lb = 30
normalize_vol = false

[Trend]
SMAs = true
KAMAs = false
kama_params = [20,2,32, 50, 2,32]
sma_lens = [100, 24]
momentum = true
momentum_periods = [120, 60]
use_scaled_returns = false

[Additional]
cols = ["cluster"]

[Training]
vol_normalized_returns = false
vol_lb = 63
target_horizon = 1


